# Generated by Django 4.1.5 on 2023-02-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user_delete_accounts_delete_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
