# Generated by Django 4.1.5 on 2023-02-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
